### ISSUE TITLE
Run single test in yaml file

### ISSUE THREAD

**Issue by MarkusPrim** [GambitBSM/gambit-test#8]
Is there currently an option to run a single defined test in a yaml file or is it only possible to run all tests at once?

**Comment by andrewfowlie** [comment]
That would be useful, but I don't think it's possible. Have a look at the bats documentation https://github.com/sstephenson/bats

You can either remove, comment out or add the skip directive to tests you don't want to perform (https://github.com/sstephenson/bats#skip-easily-skip-tests)

**Comment by andrewfowlie** [comment]
Oh sorry I misread your question. My answer was about running a single test in a *.bats file. 

Regarding testing a single output from one yaml file: that’s currently impossible and would be hard to implement.

**Comment by MarkusPrim** [comment]
No no, your first answer was to my intended question :) I figured it was that way, but I was hoping there is some option to only run the test by name or discover tests via a regex from the command line.

**Comment by andrewfowlie** [comment]
Sorry Markus, I gave you an out-of-date link before. Bats is now at:

https://github.com/bats-core/bats-core

and it looks like you want the `-f` flag for `-f, --filter     Filter test cases by names matching the regular expression`
